### ISSUE TITLE
How to run a simple example of this algorithm?

### ISSUE THREAD

**Issue by patakk** [daviddoria/PatchBasedInpainting#8]
Hello, I'd like to run ClassicalImageInpainting.cpp but I don't know where to start with building this.. 
What is the simplest way of running this?
Thanks

**Comment by daviddoria** [comment]
Unfortunately there is nothing 'simple' about this :). You need to be quite familiar with CMake and also build/install all of the required libraries.

**Comment by patakk** [comment]
that's unfortunate.
